# Generated by Django 2.0.13 on 2019-10-23 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0004_delete_trellouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.Board')),
            ],
        ),
    ]
