# Generated by Django 2.0.13 on 2019-10-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0005_boardlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.Board'),
            preserve_default=False,
        ),
    ]
