# Generated by Django 2.0.13 on 2019-10-31 08:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0007_auto_20191023_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInvite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.Board')),
            ],
        ),
    ]
