# Generated by Django 2.0.13 on 2019-11-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0013_listcard_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvite',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
