# Generated by Django 2.0.13 on 2019-10-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0003_trellouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrelloUser',
        ),
    ]
