# Generated by Django 2.0.13 on 2019-11-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0009_boardmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardlist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
