# Generated by Django 2.0.13 on 2019-11-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0010_boardlist_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardlist',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
