# Generated by Django 2.0.13 on 2019-11-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0011_auto_20191104_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvite',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardmembers',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.Board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listcard',
            name='board_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trello_drf_app.BoardList'),
            preserve_default=False,
        ),
    ]
