# Generated by Django 2.0.13 on 2019-11-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0012_auto_20191105_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
