# Generated by Django 2.0.13 on 2019-11-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0014_auto_20191114_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcard',
            name='index',
            field=models.FloatField(default=0.0),
        ),
    ]
