# Generated by Django 2.0.13 on 2019-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_drf_app', '0015_auto_20191118_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
